### ISSUE TITLE
Clear Router Crash

### ISSUE THREAD

**Issue by QmelZ** [deltanedas/routorio-old#20]
**Platform**:
windows 10 version 20h2 build 19042.685

**Mindustry Version**:
stable 121.4

**Routorio Version**: *the number please*
2.36.0

**Describe the issue**:
clear router crashes game upon placing

**Steps to reproduce, including save file if non trivial**
1. get routorio
2. place clear router

**(Crash) logs, if relevant**
[crash report](https://github.com/DeltaNedas/routorio/files/5721501/crash-report-12_21_2020_00_00_57.txt)

**Comment by deltanedas** [comment]
fixed

**Comment by pswsm** [comment]
Still crashes to me.
**Platform:** Arch Linux
**Mindustry Version:**
122.1
**Mod Version:**
2.36.0
**Issue:**
Same Issue
**Crash Report:**
https://pastebin.com/GJAtxsTU
